services:
  memento:
    container_name: memento
    build:
      context: ./
    ports:
      - 9999:9999
   # volumes:
   #   - .:/usr/src/app
   # environment:
   #   - NODE_ENV=development
    networks:
      - frontend
  
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./Nginx/Config/default.conf:/etc/nginx/conf.d/default.conf
      - ./Nginx/Sites-enabled:/etc/nginx/sites-enabled
      - ./Nginx/www:/var/www
      - ./Nginx/Log:/var/log/nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-https.entrypoints=websecure"
      - "traefik.http.routers.nginx-https.rule=Host(`memento.gregvanko.com`) || Host(`memorx.vanko.be`) "
      - "traefik.http.routers.nginx-https.tls=true"
      - "traefik.http.routers.nginx-https.tls.certresolver=cloudflare"
      - "traefik.http.services.nginx-https.loadbalancer.server.port=80"
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true